---
- name: "deploy webapp-v6"
  hosts: prod
  become: yes
  tags: webapp_v7
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_files:
  - files/secrets/credentials.yaml
  roles:
    - { role: roles/deploy-app }

